version: '3.8'

services:
  voupidir:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voupidir
    ports:
      - "9001:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
